title: Solo Faith Church Inc. Concord NC Blog
description: Updates, notes, and resources
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

url: "https://solofaithchurchincconcordnc-lgtm.github.io"
baseurl: "/blog"   
